# Generated by Django 5.1.7 on 2026-09-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatinvitation',
            name='invited_name',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
