# Generated by Django 5.1.7 on 2026-09-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seatinvitation_invited_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cf_stream_uid',
            field=models.CharField(blank=True, help_text='UID del vídeo en Cloudflare Stream (recomendado para grabaciones largas, ej. 3h)', max_length=64),
        ),
    ]
