# Generated by Django 5.1.7 on 2026-09-05 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lesson_cf_stream_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Price ID de Stripe (price_...) del curso completo. Necesario para que el webhook reconozca el pago.', max_length=64),
        ),
        migrations.AddField(
            model_name='module',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Price ID de Stripe (price_...) si este módulo se vende suelto.', max_length=64),
        ),
        migrations.AddField(
            model_name='purchase',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Solo si scope=module: qué módulo suelto se compró', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='core.module'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='scope',
            field=models.CharField(choices=[('full', 'Curso completo'), ('module', 'Módulo suelto')], default='full', max_length=10),
        ),
        migrations.CreateModel(
            name='ModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='core.module')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_access', to='core.purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'module')},
            },
        ),
    ]
