# Generated by Django 5.1.7 on 2026-09-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_stripe_price_id_module_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='attended_live',
            field=models.BooleanField(default=False, help_text='Marcado manualmente por el admin: ¿asistió a la clase en directo?'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='attended_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutos conectado en la clase en directo (manual, por ahora)'),
        ),
    ]
