# Generated by Django 5.1.7 on 2026-09-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lessonprogress_attended_live_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'verbose_name': 'Registro de actividad', 'verbose_name_plural': 'Registros de actividad'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'verbose_name': 'Progreso de clase', 'verbose_name_plural': 'Progreso de clases'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AlterModelOptions(
            name='moduleaccess',
            options={'verbose_name': 'Acceso a módulo', 'verbose_name_plural': 'Accesos a módulos'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
        migrations.AlterModelOptions(
            name='seatinvitation',
            options={'verbose_name': 'Invitación de plaza', 'verbose_name_plural': 'Invitaciones de plaza'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Perfil de alumno', 'verbose_name_plural': 'Perfiles de alumnos'},
        ),
    ]
