# Generated by Django 5.1.7 on 2026-09-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_activitylog_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='price_display',
            field=models.CharField(blank=True, help_text="Precio a mostrar en el botón de compra, ej. '405 €'.", max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='stripe_payment_link',
            field=models.URLField(blank=True, help_text='URL del Payment Link de Stripe (buy.stripe.com/...) para el botón de compra suelta.'),
        ),
    ]
