from django.contrib.auth import views as auth_views
from django.urls import path
from . import views, challenge_views

urlpatterns = [
    path("", views.home, name="home"),
    path("health/", views.health, name="health"),
    path("login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("activar/<uidb64>/<token>/", views.activate_account, name="activate_account"),
    path("post-compra/", views.post_purchase, name="post_purchase"),
    path("invitacion/<token>/", views.accept_invitation, name="accept_invitation"),
    path("campus/", views.dashboard, name="dashboard"),
    path("campus/invitar/", views.invite_seat, name="invite_seat"),
    path("campus/curso/<slug:slug>/", views.course_detail, name="course_detail"),
    path("campus/clase/<int:lesson_id>/", views.lesson_detail, name="lesson_detail"),
    path("campus/clase/<int:lesson_id>/completar/", views.complete_lesson, name="complete_lesson"),
    path("campus/challenge/", challenge_views.challenge_hub, name="challenge_hub"),
    path("campus/challenge/<int:challenge_id>/", challenge_views.challenge_detail, name="challenge_detail"),
    path("campus/challenge/<int:challenge_id>/empezar/", challenge_views.challenge_start, name="challenge_start"),
    path("campus/challenge/intento/<int:attempt_id>/", challenge_views.challenge_play, name="challenge_play"),
    path("campus/challenge/intento/<int:attempt_id>/enviar/", challenge_views.challenge_submit, name="challenge_submit"),
    path("campus/challenge/intento/<int:attempt_id>/resultado/", challenge_views.challenge_result, name="challenge_result"),
    path("media/<path:path>", views.protected_media, name="protected_media"),
    path("comprar/", views.buy_redirect, name="buy_redirect"),
    path("webhooks/stripe/", views.stripe_webhook, name="stripe_webhook"),
    path("admin-panel/", views.admin_dashboard, name="admin_dashboard"),
    path("admin-panel/alumnos/", views.admin_students, name="admin_students"),
    path("admin-panel/alumnos/nuevo/", views.admin_student_create, name="admin_student_create"),
    path("admin-panel/alumnos/<int:user_id>/", views.admin_student_detail, name="admin_student_detail"),
    path("admin-panel/alumnos/<int:user_id>/matricular/", views.admin_enroll_student, name="admin_enroll_student"),
    path("admin-panel/alumnos/<int:user_id>/eliminar/", views.admin_student_delete, name="admin_student_delete"),
    path("admin-panel/alumnos/<int:user_id>/clase/<int:lesson_id>/asistencia/", views.admin_mark_attendance, name="admin_mark_attendance"),
    path("admin-panel/contenido/", views.admin_content, name="admin_content"),
    path("admin-panel/contenido/modulo/<int:module_id>/clase/nueva/", views.admin_lesson_create, name="admin_lesson_create"),
    path("admin-panel/contenido/clase/<int:lesson_id>/editar/", views.admin_lesson_edit, name="admin_lesson_edit"),
    path("admin-panel/contenido/clase/<int:lesson_id>/publicar/", views.admin_lesson_toggle_publish, name="admin_lesson_toggle_publish"),
    path("admin-panel/contenido/clase/<int:lesson_id>/eliminar/", views.admin_lesson_delete, name="admin_lesson_delete"),
    path("admin-panel/contenido/clase/<int:lesson_id>/recurso/nuevo/", views.admin_resource_create, name="admin_resource_create"),
    path("admin-panel/contenido/recurso/<int:resource_id>/eliminar/", views.admin_resource_delete, name="admin_resource_delete"),
]
